// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type PatientInput struct {
	Name *string `json:"name"`
}

type Scan struct {
	ID           string `json:"id"`
	TimeCreated  int    `json:"timeCreated"`
	PresignedURL string `json:"presignedUrl"`
}

func (Scan) IsNode()            {}
func (this Scan) GetID() string { return this.ID }

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (User) IsNode()            {}
func (this User) GetID() string { return this.ID }
